name: Deployment

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      whatIf:
        type: boolean
        description: Enable -whatIf mode

env:
  PROFILE: 'All Reports'

jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment: Development
    container:
      image: ghcr.io/pbi-tools/pbi-tools-core:latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: pbi-tools info
        run: /app/pbi-tools/pbi-tools.core info

      - name: pbi-tools deploy (WhatIf)
        run: /app/pbi-tools/pbi-tools.core deploy . "$PROFILE" -whatIf
        env:
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}
        if: github.event.inputs.whatIf == 'true'

      - name: pbi-tools deploy
        run: /app/pbi-tools/pbi-tools.core deploy . "$PROFILE"
        env:
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}
        if: github.event.inputs.whatIf != 'true'
